In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
dataset=pd.read_csv("insurance_pre.csv")

In [3]:
dataset

      age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [4]:
dataset=pd.get_dummies(dataset,drop_first=True)

In [5]:
dataset

      age     bmi  children      charges  sex_male  smoker_yes
0      19  27.900         0  16884.92400     False        True
1      18  33.770         1   1725.55230      True       False
2      28  33.000         3   4449.46200      True       False
3      33  22.705         0  21984.47061      True       False
4      32  28.880         0   3866.85520      True       False
...   ...     ...       ...          ...       ...         ...
1333   50  30.970         3  10600.54830      True       False
1334   18  31.920         0   2205.98080     False       False
1335   18  36.850         0   1629.83350     False       False
1336   21  25.800         0   2007.94500     False       False
1337   61  29.070         0  29141.36030     False        True

[1338 rows x 6 columns]

In [6]:
dataset.columns

Index(['age', 'bmi', 'children', 'charges', 'sex_male', 'smoker_yes'], dtype='object')

In [7]:
independent=dataset[['age', 'bmi', 'children', 'sex_male', 'smoker_yes' ]]

In [8]:
dependent=dataset['charges']

In [9]:
from sklearn.ensemble import RandomForestRegressor

In [12]:
from sklearn.model_selection import GridSearchCV

param_grid = {'criterion':['friedman_mse','squared_error','absolute_error'],'max_features': ['auto','sqrt','log2'],
                'n_estimators':[10,100]}
grid=GridSearchCV(RandomForestRegressor(),param_grid,refit=True,verbose=3,n_jobs=-1)
grid.fit(independent,dependent)

Fitting 5 folds for each of 18 candidates, totalling 90 fits

C:\Users\abina\Anac\Lib\site-packages\sklearn\model_selection\_validation.py:425: FitFailedWarning:
30 fits failed out of a total of 90.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
16 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\abina\Anac\Lib\site-packages\sklearn\model_selection\_validation.py", line 732, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\abina\Anac\Lib\site-packages\sklearn\base.py", line 1144, in wrapper
    estimator._validate_params()
  File "C:\Users\abina\Anac\Lib\site-packages\sklearn\base.py", line 637, in _validate_params
    validate_parameter_constraints(
  File "C:\Users\abina\Anac\Lib\site-packages\sklearn\utils\_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'max_features' parameter of RandomForestRegressor must be an int in the range [1, inf), a float in the range (0.0, 1.0], a str among {'sqrt', 'log2'} or None. Got 'auto' instead.

--------------------------------------------------------------------------------
14 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\abina\Anac\Lib\site-packages\sklearn\model_selection\_validation.py", line 732, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\abina\Anac\Lib\site-packages\sklearn\base.py", line 1144, in wrapper
    estimator._validate_params()
  File "C:\Users\abina\Anac\Lib\site-packages\sklearn\base.py", line 637, in _validate_params
    validate_parameter_constraints(
  File "C:\Users\abina\Anac\Lib\site-packages\sklearn\utils\_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'max_features' parameter of RandomForestRegressor must be an int in the range [1, inf), a float in the range (0.0, 1.0], a str among {'log2', 'sqrt'} or None. Got 'auto' instead.

  warnings.warn(some_fits_failed_message, FitFailedWarning)
C:\Users\abina\Anac\Lib\site-packages\sklearn\model_selection\_search.py:976: UserWarning: One or more of the test scores are non-finite: [       nan        nan 0.81426589 0.8337126  0.81281983 0.83465059
        nan        nan 0.81771359 0.8338695  0.81682503 0.83236617
        nan        nan 0.8198439  0.83329103 0.81838561 0.83333732]
  warnings.warn(

GridSearchCV(estimator=RandomForestRegressor(), n_jobs=-1,
             param_grid={'criterion': ['friedman_mse', 'squared_error',
                                       'absolute_error'],
                         'max_features': ['auto', 'sqrt', 'log2'],
                         'n_estimators': [10, 100]},
             verbose=3)

In [15]:
re=grid.cv_results_

print("R_score for best parameter{}:".format(grid.best_params_))

R_score for best parameter{'criterion': 'friedman_mse', 'max_features': 'log2', 'n_estimators': 100}:

In [16]:
table=pd.DataFrame.from_dict(re)

In [17]:
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_criterion,param_max_features,param_n_estimators,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.005749,0.005708,0.000000,0.000000,friedman_mse,auto,10,"{'criterion': 'friedman_mse', 'max_features': ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,13
1,0.002310,0.003402,0.000000,0.000000,friedman_mse,auto,100,"{'criterion': 'friedman_mse', 'max_features': ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,13
2,0.373652,0.089464,0.041686,0.045501,friedman_mse,sqrt,10,"{'criterion': 'friedman_mse', 'max_features': ...",0.845290,0.753319,0.833778,0.809512,0.829430,0.814266,0.032589,11
3,3.935142,0.490803,0.126536,0.043533,friedman_mse,sqrt,100,"{'criterion': 'friedman_mse', 'max_features': ...",0.861241,0.777633,0.859491,0.826645,0.843553,0.833713,0.030705,3
4,0.372514,0.033647,0.018322,0.027176,friedman_mse,log2,10,"{'criterion': 'friedman_mse', 'max_features': ...",0.844979,0.741702,0.843985,0.813128,0.820305,0.812820,0.037734,12
5,4.136816,0.392174,0.142513,0.053774,friedman_mse,log2,100,"{'criterion': 'friedman_mse', 'max_features': ...",0.856800,0.783394,0.862958,0.827732,0.842369,0.834651,0.028378,1
6,0.000000,0.000000,0.000000,0.000000,squared_error,auto,10,"{'criterion': 'squared_error', 'max_features':...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,13
7,0.001222,0.001306,0.000000,0.000000,squared_error,auto,100,"{'criterion': 'squared_error', 'max_features':...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,13
8,0.410652,0.039929,0.055599,0.040601,squared_error,sqrt,10,"{'criterion': 'squared_error', 'max_features':...",0.836441,0.757007,0.852211,0.806284,0.836625,0.817714,0.033807,9
9,3.879794,0.706631,0.082027,0.042148,squared_error,sqrt,100,"{'criterion': 'squared_error', 'max_features':...",0.859904,0.779884,0.863065,0.825739,0.840756,0.833869,0.030193,2
10,0.378076,0.071925,0.021054,0.031045,squared_error,log2,10,"{'criterion': 'squared_error', 'max_features':...",0.844178,0.771345,0.855120,0.802119,0.811363,0.816825,0.030097,10
11,3.956696,0.381393,0.106892,0.016136,squared_error,log2,100,"{'criterion': 'squared_error', 'max_features':...",0.855598,0.780391,0.859892,0.826708,0.839243,0.832366,0.028559,6
12,0.000100,0.000200,0.000000,0.000000,absolute_error,auto,10,"{'criterion': 'absolute_error', 'max_features'...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,13
13,0.000000,0.000000,0.000000,0.000000,absolute_error,auto,100,"{'criterion': 'absolute_error', 'max_features'...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,13
14,1.210508,0.192931,0.023150,0.030709,absolute_error,sqrt,10,"{'criterion': 'absolute_error', 'max_features'...",0.840085,0.760595,0.862794,0.809077,0.826669,0.819844,0.034430,7
15,12.026556,2.200073,0.140480,0.052485,absolute_error,sqrt,100,"{'criterion': 'absolute_error', 'max_features'...",0.856343,0.778829,0.859873,0.828410,0.843001,0.833291,0.029401,5
16,1.340915,0.074417,0.022657,0.037525,absolute_error,log2,10,"{'criterion': 'absolute_error', 'max_features'...",0.847454,0.766012,0.834254,0.823891,0.820317,0.818386,0.027834,8
17,9.978891,2.073539,0.061438,0.010859,absolute_error,log2,100,"{'criterion': 'absolute_error', 'max_features'...",0.859960,0.778808,0.860431,0.823770,0.843717,0.833337,0.030383,4

In [18]:
age_input=float(input("Age:"))
bmi_input=float(input("BMI:"))
children_input=float(input("Children:"))
sex_male_input=int(input("Sex Male 0 or 1:"))
smoker_yes_input=int(input("Smoker Yes 0 or 1:"))

Age:27
BMI:32
Children:0
Sex Male 0 or 1:0
Smoker Yes 0 or 1:0

In [20]:
Future_Prediction=grid.predict([[age_input,bmi_input,children_input,sex_male_input,smoker_yes_input]])
print("Future_Prediction={}".format(Future_Prediction))

Future_Prediction=[5205.4070896]

C:\Users\abina\Anac\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(