In [1]:
#Feature Selection

In [2]:
import pandas as pd
from sklearn.model_selection import train_test_split
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
import pickle
import matplotlib.pyplot as plt
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
from sklearn.svm import SVC
from sklearn.naive_bayes import GaussianNB
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

In [3]:
dataset=pd.read_csv("prep_data.csv",index_col=None)

In [4]:
dataset

,employee_id,department,region_number,education,gender,recruitment_channel,no_of_trainings,age,previous_year_rating,length_of_service,KPIs_met_more_than_80,awards_won,avg_training_score,promotion
0,8724,Technology,26,Bachelors,m,sourcing,1,24,0.0,1,1,0,77,No
1,74430,HR,4,Bachelors,f,other,1,31,3.0,5,0,0,51,No
2,72255,Sales & Marketing,13,Bachelors,m,other,1,31,1.0,4,0,0,47,No
3,38562,Procurement,2,Bachelors,f,other,3,31,2.0,9,0,0,65,No
4,64486,Finance,29,Bachelors,m,sourcing,1,30,4.0,7,0,0,61,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17409,54192,HR,22,Below Secondary,m,other,1,24,2.0,2,0,0,47,No
17410,57239,Sales & Marketing,31,Bachelors,m,other,1,42,3.0,10,0,0,53,No
17411,73858,Sales & Marketing,25,Bachelors,m,sourcing,2,28,2.0,5,0,0,45,No
17412,64573,Technology,7,Bachelors,f,referred,2,30,5.0,6,1,0,81,No
17413,49584,HR,7,Bachelors,m,other,1,33,1.0,9,0,0,51,No

In [5]:
df2 = pd.get_dummies(dataset,drop_first=True)

In [6]:
df2

,employee_id,region_number,no_of_trainings,age,previous_year_rating,length_of_service,KPIs_met_more_than_80,awards_won,avg_training_score,department_Finance,...,department_R&D,department_Sales & Marketing,department_Technology,education_Below Secondary,education_Masters & above,education_Unknown,gender_m,recruitment_channel_referred,recruitment_channel_sourcing,promotion_Yes
0,8724,26,1,24,0.0,1,1,0,77,0,...,0,0,1,0,0,0,1,0,1,0
1,74430,4,1,31,3.0,5,0,0,51,0,...,0,0,0,0,0,0,0,0,0,0
2,72255,13,1,31,1.0,4,0,0,47,0,...,0,1,0,0,0,0,1,0,0,0
3,38562,2,3,31,2.0,9,0,0,65,0,...,0,0,0,0,0,0,0,0,0,0
4,64486,29,1,30,4.0,7,0,0,61,1,...,0,0,0,0,0,0,1,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17409,54192,22,1,24,2.0,2,0,0,47,0,...,0,0,0,1,0,0,1,0,0,0
17410,57239,31,1,42,3.0,10,0,0,53,0,...,0,1,0,0,0,0,1,0,0,0
17411,73858,25,2,28,2.0,5,0,0,45,0,...,0,1,0,0,0,0,1,0,1,0
17412,64573,7,2,30,5.0,6,1,0,81,0,...,0,0,1,0,0,0,0,1,0,0
17413,49584,7,1,33,1.0,9,0,0,51,0,...,0,0,0,0,0,0,1,0,0,0

In [7]:
indep_X=df2.drop("promotion_Yes",1)
dep_Y= df2['promotion_Yes']

#Feature Selection

In [8]:
    X_train,X_test,y_train,y_test=train_test_split(indep_X, dep_Y, test_size=0.25, random_state=0)
    sc=StandardScaler()
    X_train=sc.fit_transform(X_train)
    X_test=sc.transform(X_test)

In [9]:
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2

def PCA(X_train,X_test,n):
    from sklearn.decomposition import PCA
    pca= PCA(n_components=n)
    X_train=pca.fit_transform(X_train)
    X_test=pca.transform(X_test)
    explained_variance= pca.explained_variance_ratio_
    return X_train,X_test

In [10]:
def cm_prediction(classifier,X_test,y_test):
    y_pred=classifier.predict(X_test)
    from sklearn.metrics import confusion_matrix
    cm= confusion_matrix(y_test,y_pred)
    from sklearn.metrics import accuracy_score
    from sklearn.metrics import classification_report
    Accuracy= accuracy_score(y_test,y_pred)
    report= classification_report(y_test,y_pred)
    return classifier,Accuracy,report,cm
def logistic(X_train,y_train,X_test,y_test):
    
    classifier= LogisticRegression(random_state=0)
    classifier.fit(X_train,y_train)
    classifier,Accuracy,report,cm=cm_prediction(classifier,X_test,y_test)
    return classifier,Accuracy,report,cm
def svm_linear(X_train,y_train,X_test,y_test):
    
    classifier = SVC(kernel='linear',random_state=0,gamma='scale')
    classifier.fit(X_train,y_train)
    classifier,Accuracy,report,cm= cm_prediction(classifier,X_test,y_test)
    return classifier,Accuracy,report,cm
def svm_NL(X_train,y_train,X_test,y_test):
    classifier = SVC(kernel='rbf',random_state=0,gamma='scale')
    classifier.fit(X_train,y_train)
    classifier,Accuracy,report,cm= cm_prediction(classifier,X_test,y_test)
    return classifier,Accuracy,report,cm
def Naive(X_train,y_train,X_test,y_test):
    
    classifier = GaussianNB()
    classifier.fit(X_train,y_train)
    classifier,Accuracy,report,cm= cm_prediction(classifier,X_test,y_test)
    return classifier,Accuracy,report,cm
def knn(X_train,y_train,X_test,y_test):
    
    classifier = KNeighborsClassifier(n_neighbors=5,metric='minkowski',p=2)
    classifier.fit(X_train,y_train)
    classifier,Accuracy,report,cm= cm_prediction(classifier,X_test,y_test)
    return classifier,Accuracy,report,cm
def Decision(X_train,y_train,X_test,y_test):
    
    classifier = DecisionTreeClassifier(criterion='entropy',random_state=0)
    classifier.fit(X_train,y_train)
    classifier,Accuracy,report,cm= cm_prediction(classifier,X_test,y_test)
    return classifier,Accuracy,report,cm
def random(X_train,y_train,X_test,y_test):
    
    classifier = RandomForestClassifier(n_estimators=10,criterion='entropy',random_state=0)
    classifier.fit(X_train,y_train)
    classifier,Accuracy,report,cm= cm_prediction(classifier,X_test,y_test)
    return classifier,Accuracy,report,cm

In [11]:
def PCA_Classification(acclog,accsvml,accsvmnl,accknn,accnav,accdes,accrf): 
    
    dataframe=pd.DataFrame(index=['PCA'],columns=['Logistic','SVMl','SVMnl','KNN','Navie','Decision','Random'])
    for number,idex in enumerate(dataframe.index):      
        dataframe['Logistic'][idex]=acclog[number]       
        dataframe['SVMl'][idex]=accsvml[number]
        dataframe['SVMnl'][idex]=accsvmnl[number]
        dataframe['KNN'][idex]=accknn[number]
        dataframe['Navie'][idex]=accnav[number]
        dataframe['Decision'][idex]=accdes[number]
        dataframe['Random'][idex]=accrf[number]
    return dataframe

In [12]:
PCA = PCA(X_train, X_test,3)

acclog=[]
accsvml=[]
accsvmnl=[]
accknn=[]
accnav=[]
accdes=[]
accrf=[]

In [13]:
classifier,Accuracy,report,cm=logistic(X_train,y_train,X_test,y_test)
acclog.append(Accuracy)

classifier,Accuracy,report,cm=svm_linear(X_train,y_train,X_test,y_test)  
accsvml.append(Accuracy)
    
classifier,Accuracy,report,cm=svm_NL(X_train,y_train,X_test,y_test)  
accsvmnl.append(Accuracy)
    
classifier,Accuracy,report,cm=knn(X_train,y_train,X_test,y_test)  
accknn.append(Accuracy)
    
classifier,Accuracy,report,cm=Naive(X_train,y_train,X_test,y_test)  
accnav.append(Accuracy)
    
classifier,Accuracy,report,cm=Decision(X_train,y_train,X_test,y_test)  
accdes.append(Accuracy)
    
classifier,Accuracy,report,cm=random(X_train,y_train,X_test,y_test)  
accrf.append(Accuracy)
    
result=PCA_Classification(acclog,accsvml,accsvmnl,accknn,accnav,accdes,accrf)

In [14]:
result

     Logistic      SVMl     SVMnl       KNN     Navie Decision    Random
PCA  0.996325  0.995866  0.995866  0.994718  0.991502        1  0.999541

In [15]:
acclog

[0.99632521819017]

In [16]:
#Model creation

In [17]:
X_train,X_test,y_train,y_test=train_test_split(indep_X, dep_Y, test_size=0.25, random_state=0)

In [18]:
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [19]:
# Create and train the model
model = LogisticRegression()
model.fit(X_train_scaled, y_train)

LogisticRegression()

In [20]:
# Evaluate the model
y_pred = model.predict(X_test_scaled)
print("Model Accuracy:", accuracy_score(y_test, y_pred))

Model Accuracy: 0.99632521819017

In [21]:
from sklearn.metrics import classification_report
clf_report=classification_report(y_test,y_pred)
print(clf_report)

              precision    recall  f1-score   support

           0       1.00      1.00      1.00      4286
           1       0.86      0.91      0.89        68

    accuracy                           1.00      4354
   macro avg       0.93      0.95      0.94      4354
weighted avg       1.00      1.00      1.00      4354

In [22]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17414 entries, 0 to 17413
Data columns (total 14 columns):
employee_id              17414 non-null int64
department               17414 non-null object
region_number            17414 non-null int64
education                17414 non-null object
gender                   17414 non-null object
recruitment_channel      17414 non-null object
no_of_trainings          17414 non-null int64
age                      17414 non-null int64
previous_year_rating     17414 non-null float64
length_of_service        17414 non-null int64
KPIs_met_more_than_80    17414 non-null int64
awards_won               17414 non-null int64
avg_training_score       17414 non-null int64
promotion                17414 non-null object
dtypes: float64(1), int64(8), object(5)
memory usage: 1.9+ MB

In [23]:
previous_year_rating_input=float(input("previous_year_rating:"))
length_of_service_input=int(input("length_of_service:"))
awards_won_input=int(input("Won 0 or 1:"))

previous_year_rating:4
length_of_service:4
Won 0 or 1:1

In [24]:
Future_Prediction=model.predict([[previous_year_rating_input,length_of_service_input,awards_won_input]])
print("Future_Prediction={}".format(Future_Prediction))

ValueError: X has 3 features, but LogisticRegression is expecting 23 features as input.

In [ ]:
#Save the model

In [ ]:
import pickle
filename="finalized_model.sav"
pickle.dump(model,open(filename,'wb'))

In [ ]:
loaded_model=pickle.load(open("finalized_model.sav",'rb'))

In [ ]:
result=loaded_model.predict([[3,1,0]])

In [ ]:
result